name: Watch file
"on": push
jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - id: file_check
        run: node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_PATH_TO_WATCH: test.txt
      - if: steps.file_check.outputs.changed
        run: echo "Aye, file changed."
